{% set name = "SQcircuit" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dbff661a62f748e640d93391db0f42dc6e0172dc90262027e750cf68419b6fa0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dill >=0.3.4
    - matplotlib-base >=3.0.0
    - numpy >=1.14.2
    - python >=3.6
    - qutip >=4.3.1
    - scipy >=1.1.0

test:
  imports:
    - SQcircuit

about:
  home: https://sqcircuit.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: superconducting quantum circuit analyzer
  doc_url: https://docs.sqcircuit.org/
  dev_url: https://github.com/stanfordLINQS/SQcircuit

extra:
  recipe-maintainers:
    - taha1373
